### ISSUE TITLE
self.edgesForExtendedLayout = UIRectEdgeNone;

### ISSUE THREAD

**Issue by mixlan123** [QC-L/QCPullRefresh#1]
1.需要用到UIRectEdgeAll情况;
2.多级页面使用，刷新未结束，跳转新界面。旧界面 layer页面就会消失（特别是tabbar上的Nav上得rootVC）
3.内存泄露

**Comment by QC-L** [comment]
1.已修改, 更新下就好。
2.已修改layer消失的问题。
3.内存泄露, 使用了Instruments, 暂时未发现泄露问题, 请发个Demo参考，谢谢。如有其它疑问，欢迎issues

**Comment by mixlan123** [comment]
以上问题都得到解决。 Good!
更新后,现在内存不会泄露了.

**Comment by QC-L** [comment]
好的, 有问题时随时issues我
